<head>
<?php
    $child = $this->child;
    $isMobile = $this->mobile();
    $route = $this->routeName();
    $pageTitle = (isset($child->pageTitle)) ? $child->pageTitle : "Fotistiki - " . ucfirst($route);
    $follow = (isset($child->follow)) ? "noindex, nofollow" : "feed, follow, archieve";

    // The website's title.
    echo $this->headTitle($pageTitle);

    // The meta tags
    $description = isset($child->metaInfo['description']) ? $child->metaInfo['description'] : 'The scheduler description.';
    $keywords = isset($child->metaInfo['keywords']) ? $child->metaInfo['keywords'] : 'the, scheduler, tags';

    // We append everything to the headMeta
    $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('cache-control', 'max-age=0')
        ->appendHttpEquiv('cache-control', 'no-cache')
        ->appendHttpEquiv('expires', '0')
        ->appendHttpEquiv('expires', 'Tue, 01 Jan 1980 1:00:00 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendName('description', $description)
        ->appendName('keywords', $keywords)
        ->appendName('robots', "noindex, nofollow")
        ->appendName('language', 'en')
        ->appendName('googlebot', "noindex, nofollow");
    echo $this->headMeta();

    // We add the favicon and our stylesheets
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('images/favicon.ico')))
         ->headLink(array('rel' => 'gettext', 'type' => 'application/x-po', 'href' => $this->basePath('module/Application/language/'.$this->plugin('translate')->getTranslator()->getLocale().'.po')))
        ->prependStylesheet($this->basePath('css/jquery.dataTables.min.css'))
        ->prependStylesheet($this->basePath('css/scedit/default.min.css'))
        ->prependStylesheet(APPLICATION_ENV == "development" ? $this->basePath('css/admin-style.css') : $this->basePath('css/admin-style.min.css'));

    echo $this->headLink();

    // Some scripts the must be outputted first follow below
    ?>
<script>/*<![CDATA[*/var baseUrl="<?php echo $this->basePath(); ?>",isMobile=<?php echo $isMobile ? 'true':'false'; ?>;/*]]>*/</script>
</head>